### ISSUE TITLE
Implement protobuf.js, decode websocket and get proto file 

### ISSUE THREAD

**Issue by eperinan** [frees-io/freestyle-opscenter-webclient#12]
In the freestyle-opscenter there is a [PR](https://github.com/frees-io/freestyle-opscenter/pull/8) opened right now with the following features:

- Export the metrics serialized with proto.
- New endpoint `proto/metric` to expose the proto file with the model.

In the webclient we have to adapt to these new features. To get it, we will have to do the next steps:

- [x] Firstly we will have to use and add to the project [ProtoBuf](https://github.com/dcodeIO/ProtoBuf.js/). 
- [ ] Secondly, we have to get the proto file from freestyle-opscenter via endpoint. 
- [ ] Thirdly, we have to decode the messages that we are receiving via websocket with the proto model downloaded before.
- [ ] Fourthly, we have to change the model created previously and adapt to the new model.
- [ ] Fifthly, all have to works fine.

**Comment by eperinan** [comment]
While I was implementing the protocol buffer stuffs in freestyle-opscenter, I was doing some tests with the client. Therefore, some points of this list, are done. I am going to push the commit to the branch and then I will update the list

**Comment by eperinan** [comment]
In this commit you can see my progress https://github.com/frees-io/freestyle-opscenter-webclient/commit/802727b8f530c470f8ee4a9d31176b6d6d791e69 @calvellido

**Comment by calvellido** [comment]
Ok, thanks @eperinan, I can start working on the rest of the points.

As TypeScript is a typed language I'd like to take advantage of it and the `proto` definition files to generate models out of this definitions, but I need to read more deeply the [protobuf.js documentation](http://dcode.io/protobuf.js/#pbts-for-typescript) or [another](https://github.com/aliok/Proto2TypeScript) [alternatives](https://github.com/PeculiarVentures/tsprotobuf).

**Comment by calvellido** [comment]
As the projected work on this issue was based on a classic websockets communication model, this one is being set on hold until the work and approach taken on #18 advances and we get a clear view of the communication protocol, since some things, like the integration of [ts-protoc-gen](https://github.com/improbable-eng/ts-protoc-gen), could overlap with these described steps.
