### ISSUE TITLE
Discovery service implementation

### ISSUE THREAD

**Issue by calvellido** [frees-io/freestyle-opscenter-webclient#13]
We need to create a service to get to know which network structure is available to the client to get information from. This would eventually be an endpoint where we connect to get a tree of all the possibles microservices and nodes to show, and then select a specific one to start consuming metrics.

**Comment by eperinan** [comment]
In this branch https://github.com/frees-io/freestyle-opscenter/tree/ep-12-endpoint-microservices you have the endpoint needed.

Hitting this endpoint `http://localhost:8080/microservices` you will get the microservices and nodes availables.

The data is serialized, so you will need fecth the proto files in this endpoint `http://localhost:8080/proto/models`.

I have to change some implementation details but you can start to work on this with those endpoints.

**Comment by calvellido** [comment]
To fetch the proto describing metrics structure:
`http://localhost:8080/proto/models/metrics`

To fetch the proto associated with available nodes:
`http://localhost:8080/proto/models/microservices`

**Comment by calvellido** [comment]
In this issue, in the JS code and TS definitions generation step, we can go along with two routes, given that there are two JS runtime _Protocol Buffers_ implementations.

* On release [3.0.0](https://github.com/google/protobuf/releases/tag/v3.0.0), starting 2016, Google added node/JS support to its official `google-protobuf` library. TypeScript support is something that [was discussed](https://github.com/google/protobuf/issues/1231) at some degree in the repo issues, and even the team use TS code generation internally, but it's not yet open to the public. For this purpose then, `ts-protoc-gen` is our very best alternative.

* `Protobuf.js` is a previous third-party attempt, its origin can be traced up to even March 2013, and included TypeScript support with its [full rewritten](https://github.com/dcodeIO/protobuf.js/wiki/Changes-in-protobuf.js-6.0) 6.0.0 [release](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0) back in November 2016.

| <br>[Protobufjs](https://github.com/dcodeIO/protobuf.js)<br><br> | <br>[google-protobuf](https://github.com/google/protobuf/tree/master/js) + [ts-protoc-gen](https://github.com/improbable-eng/ts-protoc-gen)<br><br> |
| ------------- | ---------------------------------------- |
|  Much much [better](https://github.com/dcodeIO/protobuf.js/blob/57f1da64945f2dc5537c6eaa53e08e8fdd477b67/README.md#performance) **performance**, although running the benchmark locally did throw a bit less of a difference on the results, they were still massive.  | **Performance** is somehow constrained by `google-protobuf` runtime JS implementation, which in the end for encoding/decoding is more or less aligned with that of JSON.<br><br> An approach with some improvements can be consulted [here](https://github.com/google/protobuf/issues/2303). |
| Preserves **precision**, through the use of a dedicated library, [long.js](https://github.com/dcodeIO/long.js), which addresses this issue by representing a Long as two internal _parts_ of 32 bits each. <br><br> Only problem being that its use along [TypeScript definitions](https://github.com/dcodeIO/protobuf.js/issues/711) might be a [bit convoluted](https://github.com/dcodeIO/protobuf.js/issues/753). | **Precision** could be lost when using `[s/u]int64` value types on a proto descriptor, due to the discrepancy between the `number` type on JavaScript, which is based on the IEEE 754 binary64 format (Double-precision floating-point), hence only values between *-(2<sup>53</sup>-1)* and *2<sup>53</sup>-1* will be safe. Out of that range (namely values until *-(2<sup>63</sup>-1)* and *2<sup>63</sup>-1*, valid for a `int64/long` datatype) will be rounded to a near value. Some workaround can be found [here](https://github.com/improbable-eng/ts-protoc-gen/issues/17#issuecomment-324279760), and a discussion and a PR for `google-protobuf` trying to address this issue is [here](https://github.com/google/protobuf/pull/1832).<br><br> Also a [solution has been provided](https://github.com/google/protobuf/issues/3666) in the [release 3.4](https://github.com/google/protobuf/releases/tag/v3.4.0), but this one implies changes to our proto files adding a `[jstype = JS_STRING]` option to our int64 definitions.  |
| Support for **services** do exist, though the library make no assumptions on the actual transport channel used, so [the user must provide an RPC implementation](https://github.com/dcodeIO/protobuf.js#using-services). | **Services** have first-class citizen support. The use of gRPC could be easily achieved, thanks to the [grpc-web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) spec and `grpc-web-client` library, which provides [different transport channels](https://github.com/improbable-eng/grpc-web#browser-support) depending on the execution context. |
| For time when not full functionality is needed (statically generated code, JSON reflection) **final bundle size** can be reduced thanks to some [stripped down versions](https://github.com/dcodeIO/protobuf.js#distributions) offered. | **Final bundle size** can take a hit, due to this library most apparently being designed to be used on server side through node.js ([browser use](https://github.com/google/protobuf/releases/tag/v3.0.0) was somehow in the team aspirations nevertheless). |
| **Browser compatibility** [is pretty good](https://github.com/dcodeIO/protobuf.js/blob/57f1da64945f2dc5537c6eaa53e08e8fdd477b67/README.md#compatibility), even with the possibility to reach non-ES5 environments using a [polyfill](https://github.com/dcodeIO/protobuf.js/blob/master/lib/polyfill.js).  | Again, as it doesn't look like the primary goal of this library is to be used client-side, wide **browser compatibility** (while maybe not problematic) can't be something taken for granted. | 

Due to our current target of integrating freestyle-opscenter through RPC, the `google-protobuf` implementation will be used.

Should any of the advantages offered by the `Protobuf.js` library become needed to our project, a branch with the needed changes to be able to use `Protobuf.js` is gonna be set.

___
A more detailed comparison between `Protobuf.js` and JSON performance can be found [here](https://auth0.com/blog/beating-json-performance-with-protobuf/) and [here](https://github.com/brunokrebs/auth0-speed-test), and more tidbits [here](https://github.com/dcodeIO/protobuf.js/wiki/protobuf.js-vs-JSON).
