### ISSUE TITLE
Read proto files needed to communicate with backend

### ISSUE THREAD

**Issue by calvellido** [frees-io/freestyle-opscenter-webclient#28]
The backend server will be presenting the `proto` files that describe each message or RPC service, through some endpoints, e.g. ` http://localhost:8080/proto/models/microservices` to get the descriptor file of the available nodes and microservices.

To be able to fulfill issues like #13, we need to define a way of getting those proto files and be able to use them, generating the needed code to communicate with freestyle-opscenter backend.

Although we could be directly using them at runtime (thanks to the JS implementation, [Protobuf.js](https://github.com/dcodeIO/ProtoBuf.js)) as a really good advantage of using TypeScript and proto files is the chance of getting strongly typed definitions of these messages and services (with all its benefits), the proposal is to read them at build time step on the freestyle-opscenter-webclient.

**Comment by raulraja** [comment]
A freestyle-rpc service should automatically expose it's .proto definitions via http GET. this GET can happen at build time in the frontend and used to generate a typed client.
